### ISSUE TITLE
Determine correct licensing for js-comint

### ISSUE THREAD

**Issue by josteink** [redguardtoo/js-comint#24]
I've created a package forked from js-comint ([ts-comint](https://github.com/emacs-typescript/ts-comint)) and would like to add a license-file to it.

But to do so, I need to know what license this code which I've based my fork on is licensed under to ensure it is consistent or not in violation.

How about GPL3? Since that's what Emacs and the ELPA guys want everything to be?

**Comment by redguardtoo** [comment]
GPL3+ is fine. That's the version `js-comint` is using right now.
