### ISSUE TITLE
Add tests and Travis CI support

### ISSUE THREAD

**Issue by stefano-m** [redguardtoo/js-comint#7]
I think it would be good if we added tests and CI support to this repo. It would make it easier to contribute to and more confident that we are not breaking people's setups.

We could set up Travis CI jobs that test against different versions of Emacs and we could use [Cask](https://github.com/cask/cask) and [ert-runner.el](https://github.com/rejeep/ert-runner.el).

I am slowly working on adding tests on a branch of my fork now. I will submit a PR once this is done.

Of course, any other contributor is more than welcome to give a hand!

**Comment by redguardtoo** [comment]
sure, You can start add ert test cases at first.

**Comment by stefano-m** [comment]
Really sorry but clearly I am unable to contribute. I am closing this issue that is almost 5 years old.
