### ISSUE TITLE
defaullt `js-use-nvm` is nil, but still `(require 'nvm)` ?

### ISSUE THREAD

**Issue by zw963** [redguardtoo/js-comint#9]
Should we only need require nvm only set js-use-nvm is `t` ?

**Comment by redguardtoo** [comment]
yes make sense

**Comment by redguardtoo** [comment]
8397891 make nvm optional (Chen Bin)

**Comment by Wilfred** [comment]
Presumably you want to drop:

``` lisp
;;; Package-Requires: ((nvm "0.2.0"))
```

from the package header too? Once that's done, I think this issue can be closed.

**Comment by redguardtoo** [comment]
2f293bd clean code. nvm.el is optional (Chen Bin)
